server:
  port: 9015
spring:
  application:
    name: demo-authorization
  datasource:
    url: jdbc:mysql://localhost:3306/mydb_02?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#  redis:
#    host: 127.0.0.1
#    port: 6378
#    password:
#  datasource:
#    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:6378/eureka/

feign:
  hystrix:
    enabled: true
