server:
  port: 9031
spring:
  application:
    name: demo-user
  datasource:
    url: jdbc:mysql://localhost:3306/mydb_02?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true


# ====================MybatisPlus====================
#mybatisPlus:
#  globalConfig:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    idType: 3
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    fieldStrategy: 2
#    #驼峰下划线转换
#    dbColumnUnderline: true
#    #刷新mapper 调试神器
#    isRefresh: true
#    #数据库大写下划线转换
#    isCapitalMode: false
#    #逻辑删除配置
#    logicDeleteValue: 0
#    logicNotDeleteValue: 1


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.user.api.entity.**
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:6378/eureka/
security:
  oauth2:
#    client:
#      clientId: demoApp
#      clientSecret: demoAppSecret
#      userAuthorizationUri: http://localhost:9015/oauth/authorize
#      grant-type: authorization_code
#      scope: read
#      access-token-uri: http://localhost:9015/oauth/token
    resource:
        id: demo-user
        token-info-uri: http://localhost:9015/oauth/check_token
        user-info-uri: http://localhost:9015/user
        prefer-token-info: true

    client:
        client-id: air_client
        client-secret: air_client
        access-token-uri: http://localhost:9015/oauth/token
        grant-type: client_credentials,password,authorization_code
        scope: server
        user-authorization-uri: http://localhost:9015/oauth/authorize
#      jwt:
#        key-uri: http://localhost:9015/oauth/token_key
#  basic:
#    enabled: false