server:
  port: 9032
spring:
  application:
    name: demo-gateway
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#            - POST
#            - PUT
#            - DELETE
eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:6378/eureka/


